server.port=${SERVER_PORT:8084}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment}
spring.datasource.username=${DB_USER:payment}
spring.datasource.password=${DB_PASSWORD}
spring.kafka.consumer.group-id=odexa-payment
