spring.application.name=inventory
spring.config.import=classpath:runtime-defaults.properties,classpath:inventory-defaults.properties
spring.sql.init.mode=never
spring.flyway.clean-disabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-migration-naming=true
