spring.application.name=catalog
spring.config.import=classpath:runtime-defaults.properties,classpath:catalog-defaults.properties
spring.sql.init.mode=never
spring.flyway.clean-disabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-migration-naming=true
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.accept-float-as-int=false
spring.jackson.mapper.allow-coercion-of-scalars=false
